Repository VivumLab/VivumLab, pull requests merged in 2020-12, with the labels that each got.

#169 refactor(setup): fix for docker-compose location issues
  roles/vivumlab_setup/tasks/centinstall.yml
  roles/vivumlab_setup/tasks/debinstall.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority, :sweat_drops: chore

#171 refactor(tasks): minor changes to the cli prompting
  roles/vivumlab_deploy/tasks/main.yml
  tasks/AddPackageTasks.sh
  tasks/ConfigTasks.sh
  tasks/CoreTasks.sh
  tasks/DeveloperTasks.sh
  tasks/LifecyleTasks.sh
  tasks/SanityCheckTasks.sh
  tasks/ServiceTasks.sh
  tasks/TerraformTasks.sh
  tasks/UpdateTasks.sh
  tasks/UserActionTasks.sh
Labels: :beers: ready to merge, :books: ready for review, :shower: cleanup, :sweat_drops: chore

#174 fix(travis): travis build instead of pull docker images
  .travis.yml
Labels: :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority

#175 chore(readme): link fixes
  README.md
Labels: :beers: ready to merge, :hourglass_flowing_sand: priority

#176 chore(docs): fix CONTRIBUTING.md link
  .gitignore
  .travis.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority

#166 refactor(SUI): fix for SUI not working
  roles/sui/tasks/main.yml
  roles/sui/templates/config.json
  roles/sui/templates/docker-compose.sui.yml.j2
Labels: :beers: ready to merge, :shower: cleanup

#167 refactor(traefik): not exposing open ports unless required
  roles/vivumlab_config/templates/config.yml
  roles/vivumlab_config/templates/vault.yml
  roles/vivumlab_deploy/templates/docker-compose.traefik.yml.j2
  roles/vivumlab_deploy/templates/traefik.yaml
Labels: :beers: ready to merge, :books: ready for review, :hourglass_flowing_sand: priority, :key: security

#145 Service/adds hastebin
  docs/software/hastebin.md
  group_vars/all
  mkdocs.yml
  roles/hastebin/tasks/main.yml
  roles/hastebin/templates/docker-compose.hastebin.yml.j2
  roles/vivumlab_config/templates/config.yml
Labels: :beers: ready to merge, :star2: service, :star_struck: enhancement

#180 feat(service): add kutt
  docs/software/kutt.md
  group_vars/all
  mkdocs.yml
  roles/kutt/tasks/main.yml
  roles/kutt/templates/docker-compose.kutt.yml.j2
  roles/vivumlab_config/templates/config.yml
Labels: :books: ready for review, :microscope: needs testing, :star2: service

#185 fix(service): wificard main.yml
  roles/wificard/tasks/main.yml
Labels: :books: ready for review, :cricket: bug, :star2: service

#186 fix(service): kutt docker-compose.yml
  roles/kutt/templates/docker-compose.kutt.yml.j2
Labels: :books: ready for review, :cricket: bug, :star2: service

#188 refactor(service): compose formatting fixes
  roles/turtl/templates/docker-compose.turtl.yml.j2
Labels: :beers: ready to merge, :books: ready for review, :sweat_drops: chore

#189 refactor(ci): replace travis with GitHub Actions
  .github/workflows/01-pre-commit.yml
  .github/workflows/02-lint-pr.yml
  .github/workflows/03-commitlint.yml
  .github/workflows/04-release.yml
  .github/workflows/05-docker-publish.yml
  .travis.yml
Labels: :books: ready for review, :crystal_ball: future release, :hourglass_flowing_sand: priority, :sweat_drops: chore

#191 fix(ci): pre-commit should not run on push master or dev
  .github/workflows/01-pre-commit.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority

#192 chore(ci): improve workflows
  .github/workflows/02-lint-pr.yml
  .github/workflows/04-release.yml
  .github/workflows/05-docker-publish.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority, :sweat_drops: chore

#193 chore(ci): workflow release and release dry run
  .github/workflows/04-release.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug

#197 chore(ci): mirror master to dev when release
  .github/workflows/04-release.yml
  .github/workflows/06-mirror-back-to-dev.yml
Labels: :beers: ready to merge, :books: ready for review, :hourglass_flowing_sand: priority

#215 fix(service): :pencil2: fix typo
  roles/readarr/templates/docker-compose.readarr.yml.j2
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug

#213 fix(ci): fix docker-publish lint
  .github/workflows/03-release.yml
  .github/workflows/04-docker-publish.yml
  package.json
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :shower: cleanup

#217 fix(setup): use python3 with debinstall
  roles/vivumlab_setup/tasks/debinstall.yml
Labels: :books: ready for review, :hourglass_flowing_sand: priority

#214 chore(docs): add issue template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: :beers: ready to merge, :books: ready for review, :open_book: documentation

#216 chore(ci): remove double build and deploy to docker
  .github/workflows/03-release.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug

#218 refactor(service): fixes pixelfed
  roles/pixelfed/tasks/main.yml
  roles/pixelfed/templates/docker-compose.pixelfed.yml.j2
  roles/pixelfed/templates/pixelfed.env.j2
  roles/vivumlab_config/templates/config.yml
Labels: :beers: ready to merge, :books: ready for review, :star2: service

#222 chore(ci): enable multi arch docker
  .github/workflows/04-docker-publish.yml
Labels: :books: ready for review, :star_struck: enhancement

#223 fix(ci): improve docker-publish
  .github/workflows/03-release.yml
  .github/workflows/04-docker-publish.yml
Labels: :books: ready for review, :shower: cleanup

#226 chore(ci): fix docker-publish workflow
  .github/workflows/04-docker-publish.yml
Labels: :beers: ready to merge, :books: ready for review, :cricket: bug, :hourglass_flowing_sand: priority

#229 refactor(core): removing vagrant
  .gitignore
  CONTRIBUTING.md
  Vagrantfile
  group_vars/vagrant
  host_vars/vagrant
  mkdocs.yml
  website/docs/dev/Vagrant.md
  website/sidebars.js
Labels: :beers: ready to merge, :books: ready for review, :shower: cleanup, :sweat_drops: chore

#232 chore(ci): adding Sanity Checks
  .github/workflows/01-sanity-checks.yml
  .github/workflows/02-pre-commit.yml
Labels: :books: ready for review, :hourglass_flowing_sand: priority

#237 refactor(docs): migrate completely from mkdocs
  CONTRIBUTING.md
  mkdocs.yml
  package_template/mkdocs.yml
  package_template/new_service/new_service.md
  roles/tor/.gitignore
  website/docs/dev/Adding-Services.md
  website/package.json
  website/yarn.lock
  yamllint.conf
Labels: :shower: cleanup, :sos: help wanted, :sweat_drops: chore

#239 fix(security): fix insecure traefik port
  roles/vivumlab_deploy/templates/traefik.yaml
Labels: :books: ready for review, :hourglass_flowing_sand: priority, :key: security, :microscope: needs testing
