Repository VivumLab/VivumLab, pull requests merged in 2020-11, with the labels that each got.

#146 refactor(ssh): fix for sshkey check
  tasks/SanityCheckTasks.sh
Labels: ready for review

#147 refactor(precommit): fix for Vivum not recognising precommit install
  tasks/SanityCheckTasks.sh
Labels: ready for review

#148 chore(core): cleanup helperFunctions.sh
  tasks/helperFunctions.sh
Labels: cleanup, ready for review

#118 fix(core): add new package wizard
  .gitignore
  mkdocs.yml
  package_template/config.yml
  package_template/mkdocs.yml
  roles/vivumlab_config/templates/config.yml
  tasks/AddPackageTasks.sh
Labels: enhancement, ready for review

#149 chore(core): helpeFunctions.sh fix
  tasks/helperFunctions.sh
Labels: bug, chore, ready for review

#133 feat(core): allows user to create/use different config files
  .gitignore
  playbook.ci_config.yml
  roles/vivumlab_config/tasks/main.yml
  tasks/ConfigTasks.sh
  tasks/CoreTasks.sh
  tasks/LifecyleTasks.sh
  tasks/SanityCheckTasks.sh
  tasks/TerraformTasks.sh
  tasks/UpdateTasks.sh
  tasks/UserActionTasks.sh
  yamllint.conf
Labels: needs testing

#144 WIP: chore(tasks): update vlab -t
  README.md
  tasks/CoreTasks.sh
  tasks/DeveloperTasks.sh
  tasks/LifecyleTasks.sh
  tasks/SanityCheckTasks.sh
Labels: cleanup, ready for review, ready to merge

#158 refactor(core):Improving SSH command syntax
  tasks/LifecyleTasks.sh
  tasks/ServiceTasks.sh
  tasks/UserActionTasks.sh
Labels: ready for review, ready to merge

#159 chore(readme): update Logo
  README.md
Labels: ready for review, ready to merge

#163 refactor(config): unbound variable fix
  tasks/helperFunctions.sh
Labels: :beers: ready to merge, :books: ready for review, :hourglass_flowing_sand: priority

#168 refactor(wireguard): fixed minor syntax/typos in wireguard
  roles/vivumlab_wireguard/tasks/main.yml
Labels: :beers: ready to merge, :books: ready for review, :shower: cleanup, :sweat_drops: chore

#170 refactor(config): remove unnecessary commenting
  docs/dev/Developer-Tips.md
  roles/vivumlab_config/templates/config.yml
Labels: :beers: ready to merge, :books: ready for review, :open_book: documentation, :shower: cleanup, :sweat_drops: chore

#165 refactor(install): Create ubuntu specific installer
  roles/vivumlab_setup/tasks/main.yml
  roles/vivumlab_setup/tasks/ubuntuinstall.yml
Labels: :beers: ready to merge, :books: ready for review, :star_struck: enhancement

#164 refactor(install): fixes some issues with setuptools
  roles/vivumlab_setup/tasks/debinstall.yml
Labels: :beers: ready to merge, :books: ready for review, :microscope: needs testing
