Repository VivumLab/VivumLab, pull requests merged in 2021-01, with the labels that each got.

#238 refactor(services): removing unsupported services
  .gitignore
  group_vars/all
  roles/bulletnotes/tasks/main.yml
  roles/bulletnotes/templates/docker-compose.bulletnotes.yml.j2
  roles/inventario/tasks/main.yml
  roles/inventario/templates/docker-compose.inventario.yml.j2
  roles/kibitzr/tasks/main.yml
  roles/kibitzr/templates/docker-compose.kibitzr.yml.j2
  roles/mashio/tasks/main.yml
  roles/mashio/templates/docker-compose.mashio.yml.j2
  roles/vivumlab_config/templates/config.yml
  website/docs/Welcome.md
  website/docs/dev/Adding-Services.md
  website/docs/software/bulletnotes.md
  website/docs/software/inventario.md
  website/docs/software/kibitzr.md
  website/docs/software/mashio.md
  website/sidebars.js
Labels: :books: ready for review, :shower: cleanup, :star2: service

#243 refactor(service): converting OwnPhotos to LibrePhotos
  group_vars/all
  roles/librephotos/tasks/main.yml
  roles/librephotos/templates/docker-compose.librephotos.yml.j2
  roles/ownphotos/tasks/main.yml
  roles/ownphotos/templates/docker-compose.ownphotos.yml.j2
  roles/photoprism/templates/docker-compose.photoprism.yml.j2
  roles/vivumlab_config/templates/config.yml
  roles/vivumlab_config/templates/vault.yml
  website/docs/Welcome.md
  website/docs/software/librephotos.md
  website/docs/software/ownphotos.md
  website/sidebars.js
Labels: :books: ready for review, :star2: service

#250 feat(automation): automatically add owner of merged PR as a contributor
  .github/invite-contributors.yml
Labels: :books: ready for review, :star_struck: enhancement

#249 feat(CODEOWNERS): add CODEOWNERS file and basic rules
  .github/CODEOWNERS
Labels: :books: ready for review, :key: security, :star_struck: enhancement

#246 fix(release): auto trigger release
  .github/workflows/03-release.yml
Labels: :books: ready for review, :question: question, :star_struck: enhancement

#234 fix(service): update nextcloud
  roles/nextcloud/files/build/Dockerfile
  roles/nextcloud/files/build/entrypoint.sh
  roles/nextcloud/files/web/Dockerfile
  roles/nextcloud/files/web/nginx.conf
  roles/nextcloud/tasks/main.yml
  roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
  roles/vivumlab_config/templates/config.yml
  roles/vivumlab_deploy/tasks/conf.d/middlewares.yaml
  roles/vivumlab_deploy/templates/labels.j2
Labels: :books: ready for review, :cricket: bug, :microscope: needs testing, :star2: service

#253 fix: fixes WIP failing status
  .github/pr-status-label.json
  .github/workflows/01-sanity-checks.yml
Labels: :books: ready for review, :star_struck: enhancement

#251 refactor(service): updating portainer
  roles/portainer/templates/docker-compose.portainer.yml.j2
  roles/vivumlab_config/templates/config.yml
Labels: :books: ready for review, :microscope: needs testing, :star2: service, :sweat_drops: chore

#264 fix: fix hardcoded config paths
  package_template/roles/template/templates/docker-compose.template.yml.j2
  roles/authelia/templates/authelia_config-tor.yml.j2
  roles/authelia/templates/authelia_config.yml.j2
  roles/authelia/templates/docker-compose.authelia.yml.j2
  roles/bookstack/templates/docker-compose.bookstack.yml.j2
  roles/codimd/tasks/main.yml
  roles/codimd/templates/docker-compose.codimd.yml.j2
  roles/digikam/templates/docker-compose.digikam.yml.j2
  roles/drone/templates/docker-compose.drone.yml.j2
  roles/firefly_iii/templates/docker-compose.firefly_iii.yml.j2
  roles/freshrss/templates/docker-compose.freshrss.yml.j2
  roles/funkwhale/templates/docker-compose.funkwhale.yml.j2
  roles/gitea/templates/docker-compose.gitea.yml.j2
  roles/gitlab/templates/docker-compose.gitlab.yml.j2
  roles/guacamole/templates/docker-compose.guacamole.yml.j2
  roles/homeassistant/tasks/main.yml
  roles/homeassistant/templates/system_config.json
  roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
  roles/huginn/templates/docker-compose.huginn.yml.j2
  roles/invoiceninja/templates/docker-compose.invoiceninja.yml.j2
  roles/keycloak/templates/docker-compose.keycloak.yml.j2
  roles/kutt/templates/docker-compose.kutt.yml.j2
  roles/librephotos/templates/docker-compose.librephotos.yml.j2
  roles/massivedecks/templates/docker-compose.massivedecks.yml.j2
  roles/matomo/templates/docker-compose.matomo.yml.j2
  roles/mayan/templates/docker-compose.mayan.yml.j2
  roles/miniflux/templates/docker-compose.miniflux.yml.j2
  roles/monicahq/templates/docker-compose.monicahq.yml.j2
  roles/nextcloud/templates/docker-compose.nextcloud.yml.j2
  roles/paperless/templates/docker-compose.paperless.yml.j2
  roles/photoprism/templates/docker-compose.photoprism.yml.j2
  roles/piwigo/templates/docker-compose.piwigo.yml.j2
  roles/pixelfed/templates/docker-compose.pixelfed.yml.j2
  roles/pleroma/templates/docker-compose.pleroma.yml.j2
  roles/shinobi/templates/docker-compose.shinobi.yml.j2
  roles/snibox/templates/docker-compose.snibox.yml.j2
  roles/teedy/templates/docker-compose.teedy.yml.j2
  roles/turtl/templates/docker-compose.turtl.yml.j2
  roles/vivumlab_config/templates/ansible_bash.vars
  roles/wallabag/templates/docker-compose.wallabag.yml.j2
  roles/webdavserver/templates/docker-compose.webdavserver.yml.j2
  roles/webtrees/templates/docker-compose.webtrees.yml.j2
  roles/webvirtmgr/templates/docker-compose.webvirtmgr.yml.j2
  roles/zammad/templates/docker-compose.zammad.yml.j2
  roles/zulip/templates/docker-compose.zulip.yml.j2
  tasks/utils.rb
  ui.rb
  website/docs/software/mailu.md
  website/docs/software/pleroma.md
Labels: :books: ready for review, :cricket: bug

#265 feat: Skip setup tag after first setup.
  .prettierrc
  playbook.stop.yml
  roles/vivumlab_deploy/tasks/main.yml
  roles/vivumlab_deploy/templates/service.j2
  tasks/utils.rb
Labels: :books: ready for review, :star_struck: enhancement

#262 fix: add enable wait_for_connection activated via variable
  playbook.remove.yml
  playbook.restart.yml
  playbook.restore.yml
  playbook.service-edit.yml
  playbook.stop.yml
  playbook.vivumlab.yml
  roles/vivumlab_config/templates/config.yml
  tasks/service.rb
  website/docs/FAQ-Troubleshoot.md
Labels: :books: ready for review, :cricket: bug

#268 fix: change https_only to hsts default true
  .github/workflows/04-docker-publish.yml
  Gemfile
  Gemfile.lock
  package_template/config.yml
  playbook.restart.yml
  playbook.restore.yml
  roles/authelia/tasks/main.yml
  roles/calibre/templates/docker-compose.calibre.yml.j2
  roles/funkwhale/templates/docker-compose.funkwhale.yml.j2
  roles/gitlab/templates/docker-compose.gitlab.yml.j2
  roles/invoiceninja/templates/docker-compose.invoiceninja.yml.j2
  roles/mailu/templates/docker-compose.mailu.yml.j2
  roles/mayan/templates/docker-compose.mayan.yml.j2
  roles/ombi/templates/docker-compose.ombi.yml.j2
  roles/syncthing/templates/docker-compose.syncthing.yml.j2
  roles/turtl/templates/docker-compose.turtl.yml.j2
  roles/ubooquity/templates/docker-compose.ubooquity.yml.j2
  roles/vivumlab_config/templates/config.yml
  roles/vivumlab_deploy/tasks/conf.d/middlewares.yaml
  roles/vivumlab_deploy/tasks/main.yml
  roles/vivumlab_deploy/templates/docker-compose.traefik.yml.j2
  roles/vivumlab_deploy/templates/labels.j2
  roles/vivumlab_remove/tasks/main.yml
  roles/vivumlab_restore/tasks/main.yml
  tasks/addpackage.rb.old
  tasks/lib/dynamic_namespaces.rb
  tasks/locales/de.yml
  tasks/locales/en.yml
  tasks/locales/es.yml
  tasks/locales/fr.yml
  tasks/sanity_checks.rb
  tasks/service.rb
  website/docs/software/adguardhome.md
  website/docs/software/airsonic.md
  website/docs/software/apache2.md
  website/docs/software/authelia.md
  website/docs/software/barcodebuddy.md
  website/docs/software/beets.md
  website/docs/software/bitwarden.md
  website/docs/software/bookstack.md
  website/docs/software/calibre.md
  website/src/pages/index.js
Labels: :beers: ready to merge, :key: security, :sos: help wanted, :star_struck: enhancement

#279 fix: Fixes issue with modulo math that caused an error
  tasks/service.rb
Labels: :books: ready for review

#280 fix: new config command
  tasks/utils.rb
Labels: :books: ready for review

#287 fix: code-server's password param is wrong.
  roles/codeserver/templates/docker-compose.codeserver.yml.j2
Labels: :books: ready for review

#303 fix: fixes bad prompt, and logic surrounding the creation of a missing vault pass
  tasks/core.rb
  tasks/lib/config_file_utils.rb
  tasks/sanity_checks.rb
Labels: :books: ready for review, :hourglass_flowing_sand: priority

#302 fix: vlab throws uninitialized constant for unknown service.
  tasks/locales/en.yml
  tasks/service.rb
Labels: :books: ready for review

#296 feat: colorizes vlab service list
  docker/Dockerfile
  docker/Dockerfile.dev
  tasks/lib/config_file_utils.rb
  tasks/locales/en.yml
  tasks/service.rb
Labels: :books: ready for review

#308 fix: remove taskfile
  Taskfile
Labels: :books: ready for review

#318 fix: skip tags setup
  tasks/core.rb
  tasks/service.rb
  tasks/utils.rb
Labels: :books: ready for review, :cricket: bug, :microscope: needs testing

#314 fix(docker): fix dockerfile
  .pre-commit-config.yaml
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/docker-entrypoint.sh
  docker/motd
  launch.sh
Labels: :cricket: bug, :microscope: needs testing

#336 fix: restic docker-compose.yml
  roles/restic/templates/docker-compose.restic.yml.j2
  website/docs/core/Backup.md
Labels: :books: ready for review, :cricket: bug
